app = "fitlo"
primary_region = "fra"

[build]

[deploy]
  # Migrations now handled via Supabase CLI before deployment

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 6
  max_machines_running = 20       
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

[balance]
  regions = ["fra", "ams"] 