# fly.toml app configuration file generated for storyworth-voice-recordings on 2025-08-19T19:37:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'storyworth-voice-recordings'
primary_region = 'fra'

[build]

[deploy]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
